name: 'Update Election Datasets'

on:
  schedule:
    - cron: "0 10 * * *"
jobs:
  update_election:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRETS }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run data pipeline script
        run: |
          python run_daily_pipeline.py
        shell: bash
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            # Include all csv files from the `data` directory
            file-path: |
              data/*.csv
              figures/*.png
            commit-msg: Daily election update
            github-token: ${{ secrets.SECRETS }}
